[elasticsearch_resource_encoder]
type = "SandboxEncoder"
filename = "lua_encoders/es_payload.lua"

    [elasticsearch_resource_encoder.config]
	index = "ceilometer_resource"
	type_name = "%{source}"
	id = "%{resource_id}"