[elasticsearch_meter_output]
type = "ElasticSearchOutput"
message_matcher = "Type == 'resource'"
encoder = "elasticsearch_meter_encoder"

flush_interval = 5000
flush_count = 10

server = "http://127.0.0.1:9200"

use_buffering = true

[elasticsearch_meter_output.buffering]
max_buffer_size = 1073741824
max_file_size = 134217728
full_action = "drop"
