[ceilometer_influxdb_output]
type = "HttpOutput"
message_matcher = "Fields[payload_type] == 'txt' && Fields[payload_name] == 'sample'"
encoder = "influxdb_encoder"
address = "http://127.0.0.1:8086/write?db=ceilometer&precision=ns"
username = "root"
password = "root"
http_timeout = 5000
method = "POST"
use_buffering = true

[ceilometer_influxdb_output.buffering]
max_buffer_size = 1073741824
max_file_size = 134217728
full_action = "drop"

[ceilometer_influxdb_output.headers]
    Content-Type = ["application/x-www-form-urlencoded"]
  
